version: 2
jobs:
  build:
    docker:
    - image: perl:5
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: shinycms
        MYSQL_USER: shinyuser
        MYSQL_PASSWORD: shinypass
        MYSQL_HOSTNAME: 127.0.0.1
        TAR_OPTIONS: --no-same-owner
        TEST_POD: 1
        TEST_CRITIC: 1
        RECAPTCHA_OFF: 1

    steps:
    - checkout

    - restore_cache:
        key: cache-dependencies

    - run:
        name: Install distro packages
        command: |
            apt-get update && apt-get install -y \
                gcc make cpanminus libxml2 libxml2-dev libdbd-mysql-perl

    - run:
        name: Install dependencies from CPAN
        command: |
            cpanm --quiet --no-prompt --no-interactive --notest \
            Module::Install::Catalyst DBD::mysql && \
            cpanm --quiet --no-prompt --no-interactive --notest --installdeps .

    - save_cache:
        key: cache-dependencies
        paths:
            - ~/perl5

    - run:
        name: Set up database
        command: bash bin/database/build-with-demo-data

    - run:
        name: Run tests with coverage analysis
        command: bash bin/test/run-tests-with-coverage

    - run:
        name: Generate coverage data for codecov
        command: cover -report codecov
